// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainTimetable.Data;

#nullable disable

namespace TrainTimetable.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831161123_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainTimetable.Data.Entities.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Croatia"
                        });
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Line", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<int>("TrainID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TrainID");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            LineNumber = 1,
                            TrainID = 1
                        },
                        new
                        {
                            ID = 2,
                            LineNumber = 2,
                            TrainID = 2
                        });
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Station", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BaseStationID")
                        .HasColumnType("int");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("BaseStationID");

                    b.HasIndex("CountryID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CountryID = 1,
                            Name = "Varaždin"
                        },
                        new
                        {
                            ID = 2,
                            BaseStationID = 1,
                            CountryID = 1,
                            Name = "Turčin"
                        },
                        new
                        {
                            ID = 3,
                            BaseStationID = 1,
                            CountryID = 1,
                            Name = "Doljan"
                        },
                        new
                        {
                            ID = 4,
                            BaseStationID = 1,
                            CountryID = 1,
                            Name = "Krušljevec"
                        },
                        new
                        {
                            ID = 5,
                            BaseStationID = 1,
                            CountryID = 1,
                            Name = "Čakovec"
                        });
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Stop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("LineID")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StationID");

                    b.HasIndex("LineID", "Order")
                        .IsUnique();

                    b.HasIndex("LineID", "StationID")
                        .IsUnique();

                    b.ToTable("Stops");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartureTime = new TimeOnly(10, 35, 0),
                            LineID = 1,
                            Order = 1,
                            StationID = 4
                        },
                        new
                        {
                            ID = 2,
                            ArrivalTime = new TimeOnly(10, 50, 0),
                            DepartureTime = new TimeOnly(10, 55, 0),
                            LineID = 1,
                            Order = 2,
                            StationID = 3
                        },
                        new
                        {
                            ID = 3,
                            ArrivalTime = new TimeOnly(11, 10, 0),
                            DepartureTime = new TimeOnly(11, 15, 0),
                            LineID = 1,
                            Order = 3,
                            StationID = 2
                        },
                        new
                        {
                            ID = 4,
                            ArrivalTime = new TimeOnly(11, 30, 0),
                            LineID = 1,
                            Order = 4,
                            StationID = 1
                        },
                        new
                        {
                            ID = 5,
                            DepartureTime = new TimeOnly(12, 35, 0),
                            LineID = 2,
                            Order = 1,
                            StationID = 3
                        },
                        new
                        {
                            ID = 6,
                            ArrivalTime = new TimeOnly(12, 50, 0),
                            DepartureTime = new TimeOnly(12, 55, 0),
                            LineID = 2,
                            Order = 2,
                            StationID = 1
                        },
                        new
                        {
                            ID = 7,
                            ArrivalTime = new TimeOnly(13, 10, 0),
                            LineID = 2,
                            Order = 3,
                            StationID = 5
                        });
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Train", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<int>("TrainManufacturerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TrainManufacturerID");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "E.403",
                            SeatCount = 60,
                            TrainManufacturerID = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "S Stock",
                            SeatCount = 50,
                            TrainManufacturerID = 2
                        },
                        new
                        {
                            ID = 3,
                            Name = "X65",
                            SeatCount = 76,
                            TrainManufacturerID = 3
                        });
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.TrainManufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrainManufacturer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "FS Trenitalia"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Bombardier Transportation"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Alstom"
                        });
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Line", b =>
                {
                    b.HasOne("TrainTimetable.Data.Entities.Train", "Train")
                        .WithMany("Lines")
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Station", b =>
                {
                    b.HasOne("TrainTimetable.Data.Entities.Station", "BaseStation")
                        .WithMany()
                        .HasForeignKey("BaseStationID");

                    b.HasOne("TrainTimetable.Data.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseStation");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Stop", b =>
                {
                    b.HasOne("TrainTimetable.Data.Entities.Line", "Line")
                        .WithMany("Stops")
                        .HasForeignKey("LineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainTimetable.Data.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Train", b =>
                {
                    b.HasOne("TrainTimetable.Data.Entities.TrainManufacturer", "TrainManufacturer")
                        .WithMany("Trains")
                        .HasForeignKey("TrainManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainManufacturer");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Line", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Train", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.TrainManufacturer", b =>
                {
                    b.Navigation("Trains");
                });
#pragma warning restore 612, 618
        }
    }
}
