// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainTimetable.Data;

#nullable disable

namespace TrainTimetable.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829170844_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainTimetable.Data.Entities.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Line", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("FirstStopID")
                        .HasColumnType("int");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FirstStopID");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Station", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BaseStationID")
                        .HasColumnType("int");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BaseStationID");

                    b.HasIndex("CountryID");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Stop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LineID")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LineID");

                    b.HasIndex("StationID");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Train", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Line", b =>
                {
                    b.HasOne("TrainTimetable.Data.Entities.Stop", "FirstStop")
                        .WithMany()
                        .HasForeignKey("FirstStopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstStop");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Station", b =>
                {
                    b.HasOne("TrainTimetable.Data.Entities.Station", "BaseStation")
                        .WithMany()
                        .HasForeignKey("BaseStationID");

                    b.HasOne("TrainTimetable.Data.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID");

                    b.Navigation("BaseStation");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Stop", b =>
                {
                    b.HasOne("TrainTimetable.Data.Entities.Line", null)
                        .WithMany("Stops")
                        .HasForeignKey("LineID");

                    b.HasOne("TrainTimetable.Data.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TrainTimetable.Data.Entities.Line", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
